<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRjq5tex\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRjq5tex/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerRjq5tex.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerRjq5tex\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerRjq5tex\appDevDebugProjectContainer([
    'container.build_hash' => 'Rjq5tex',
    'container.build_id' => '1fc35053',
    'container.build_time' => 1731152265,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRjq5tex');
