services:
  pasmanteria-fryderyka:
    image: ghcr.io/kanareklife/pasmanteria_fryderyka
    restart: unless-stopped
    ports:
      - "19304:443"
    environment:
      DB_HOST: BE_193044_pasmanteria-fryderyka-db
      DB_NAME: ${MARIADB_DATABASE}
      DB_USER: ${MARIADB_USER}
      DB_PASSWORD: ${MARIADB_PASSWORD}
      RESTORE_DB: ${RESTORE_DB}
      DOMAIN: ${DOMAIN}
      SECRET: ${SECRET}
      COOKIE_KEY: ${COOKIE_KEY}
      COOKIE_IV: ${COOKIE_IV}
      NEW_COOKIE_KEY: ${NEW_COOKIE_KEY}
      PRESTASHOP_URL: ${PRESTASHOP_URL}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      API_KEY: ${API_KEY}
      DEV_MODE: "false"
    networks:
      - pasmanteria-fryderyka
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 256M
        reservations:
          cpus: "0.25"
          memory: 256M

  pasmanteria-fryderyka-db:
    image: mariadb:11.5
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    networks:
      - pasmanteria-fryderyka
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 256M
        reservations:
          cpus: "0.25"
          memory: 256M

networks:
  pasmanteria-fryderyka:
    driver: overlay
