<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCmypxwu\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCmypxwu/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerCmypxwu.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerCmypxwu\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerCmypxwu\appProdProjectContainer([
    'container.build_hash' => 'Cmypxwu',
    'container.build_id' => '77927e7d',
    'container.build_time' => 1731152175,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCmypxwu');
