services:
  prestashop-dev:
    build:
      context: .
      target: prestashop-dev
    restart: always
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./prestashop:/app/prestashop
      - caddy-data:/data/caddy
      - caddy-config:/config/caddy
    environment:
      DB_HOST: prestashop-db
      DB_NAME: ${MARIADB_DATABASE}
      DB_USER: ${MARIADB_USER}
      DB_PASSWORD: ${MARIADB_PASSWORD}
      DOMAIN: ${DOMAIN}
      SECRET: ${SECRET}
      COOKIE_KEY: ${COOKIE_KEY}
      COOKIE_IV: ${COOKIE_IV}
      NEW_COOKIE_KEY: ${NEW_COOKIE_KEY}
      DEV_MODE: "true"
    depends_on:
      - prestashop-db

  prestashop-db:
    image: mariadb:11.5
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - prestashop-db-data:/var/lib/mysql

  prestashop-db-backup-restore:
    image: mariadb:11.5
    restart: on-failure
    environment:
      DB_NAME: ${MARIADB_DATABASE}
      DB_USER: ${MARIADB_USER}
      DB_PASSWORD: ${MARIADB_PASSWORD}
      DB_HOST: ${MARIADB_HOST}
      PRESTASHOP_URL: ${PRESTASHOP_URL}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      API_KEY: ${API_KEY}
    volumes:
      - ./db_backup:/app/db_backup
    depends_on:
      - prestashop-db
    command:
      - /app/db_backup/db_manager.sh
    working_dir: /app/db_backup

volumes:
  prestashop-db-data:
  caddy-data:
  caddy-config:
