services:
  prestashop:
    #image: ghcr.io/kanareklife/pasmanteria_fryderyka
    build:
      context: .
      target: prestashop
    restart: always
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - prestashop-images:/app/prestashop/img
      - caddy-data:/data/caddy
      - caddy-config:/config/caddy
    environment:
      DB_HOST: prestashop-db
      DB_NAME: ${MARIADB_DATABASE}
      DB_USER: ${MARIADB_USER}
      DB_PASSWORD: ${MARIADB_PASSWORD}
      RESTORE_DB: ${RESTORE_DB}
      DOMAIN: ${DOMAIN}
      SECRET: ${SECRET}
      COOKIE_KEY: ${COOKIE_KEY}
      COOKIE_IV: ${COOKIE_IV}
      NEW_COOKIE_KEY: ${NEW_COOKIE_KEY}
      PRESTASHOP_URL: ${PRESTASHOP_URL}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      API_KEY: ${API_KEY}
      DEV_MODE: "false"
    depends_on:
      prestashop-db:
        condition: service_healthy

  prestashop-db:
    image: mariadb:11.5
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - prestashop-db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  prestashop-db-data:
  prestashop-images:
  caddy-data:
  caddy-config:
