services:
  prestashop:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./prestashop:/app/prestashop
    depends_on:
      - prestashop-db

  prestashop-db:
    image: mariadb:11.5
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - prestashop-db-data:/var/lib/mysql

volumes:
  prestashop-db-data:
