services:
  prestashop-dev:
    build:
      context: .
      target: prestashop-dev
    restart: always
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./prestashop:/app/prestashop
    environment:
      DB_HOST: prestashop-db
      DB_NAME: ${MARIADB_DATABASE}
      DB_USER: ${MARIADB_USER}
      DB_PASSWORD: ${MARIADB_PASSWORD}
      DOMAIN: ${DOMAIN}
      SECRET: ${SECRET}
      COOKIE_KEY: ${COOKIE_KEY}
      COOKIE_IV: ${COOKIE_IV}
      NEW_COOKIE_KEY: ${NEW_COOKIE_KEY}
      DEV_MODE: "true"
    depends_on:
      - prestashop-db

  prestashop-db:
    image: mariadb:11.5
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - prestashop-db-data:/var/lib/mysql

  prestashop-db-backup-restore:
    build:
      context: .
      dockerfile: db_backup/Dockerfile
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_HOST: ${MARIADB_HOST}
    volumes:
      - ./db_backup:/app/db_backup
    depends_on:
      - prestashop-db

volumes:
  prestashop-db-data:
